import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex justify-center'>
        <img className='rounded-full w-60 h-auto items-center' 
          src="https://github.com/aminriqky.png" 
          alt="Profile Picture" 
        />
      </div>
    </div>
  )
}

export default Home
